name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      
permissions:
      contents: write
      
jobs:      
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install # Adjust this command if you're using a different package manager

      - name: Run build script
        run: npm run build # Adjust this command to match your build script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # Path to the directory you want to deploy
          publish_branch: gh-pages # The branch to deploy to